version: '3.8'

services:
  streamlit_app:
    build: ./uploader
    container_name: fileupload
    ports:
      - "5000:5000"
    volumes:
      - uploads:/tmp/uploads
      - outputs:/sandbox-output:ro  
      # - /var/run/docker:/var/run/docker 
    networks:
      sandbox_net:
        ipv4_address: 172.10.1.2
  
  dispatcher:
    container_name: dispatcher
    build: ./dispatcher
    depends_on:
      - streamlit_app
    volumes:
      - uploads:/tmp/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    
  report:
    build:
      context: ./report-generator
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - sandbox_net
    depends_on:
      - dispatcher


networks:
  sandbox_net:
    name: sandbox_net
    driver: bridge
    ipam:
      config:
        - subnet: "172.10.1.0/24"


volumes:
  uploads:
    name: "streamlit-uploads"
  outputs:
    name: "sandbox-output"