FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update &&  apt-get install -y libmagic-dev

RUN pip install --upgrade pip && pip install -r requirements.txt 

COPY . .

EXPOSE 5000

CMD ["streamlit","run","setup.py"]